### ISSUE TITLE
Why not just create a bot account?

### ISSUE THREAD

**Issue by MrBartusek** [Auxority/galaxy-life-rpc#2]
I was wondering is there any reason why you are using RCP instead of just making a bot? You are just hosting a real discord account that has this thing running.  I'm quite sure that the setup that you have here is first off all [against tos](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-). Second of all, I can not really invite this account to my server? If I want to have server status showing up on my server I need to go thought the pain of setting this up instead of just simply inviting the bot

**Comment by Auxority** [comment]
Hi there,

This project was made to run on your own account, just so you can easily find the status. The code is open-source, so you are free to convert it to a discord bot. Should only take 10 minutes if you're an experienced developer.
A rich presence application is not against the Discord ToS, just so you know. If you want to run this 24/7, I recommend using an alt account and a VPS with linux and discord installed.

**Comment by Auxority** [comment]
Here ya go: https://github.com/Auxority/galaxy-life-bot

**Comment by MrBartusek** [comment]
Thank you!
